import { ArrowDown, ArrowUp, ImagePlus, Plus, Trash2 } from "lucide-react";
import { uploadFile } from "../../api/admin";
import type { ContentBlock, ContentBlockType, ProductSpec, VendorMedia } from "../../types/api";
import { ProtectedMediaImage } from "./ProtectedMediaImage";

export function VendorMediaEditor({ value, onChange }: { value: VendorMedia[]; onChange: (rows: VendorMedia[]) => void }) {
  const update = (index: number, patch: Partial<VendorMedia>) => onChange(value.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= value.length) return; const next = [...value]; [next[index], next[target]] = [next[target], next[index]]; onChange(next.map((row, rowIndex) => ({ ...row, sortOrder: rowIndex + 1 }))); };
  const upload = (file: File) => uploadFile(file).then((result) => onChange([...value, { kind: "factory" as const, assetId: result.assetId, url: result.previewUrl, caption: "", sortOrder: value.length + 1 }])).catch(() => window.alert("图片上传失败，请检查格式、尺寸或网络后重试"));
  return <div className="structured-editor"><div className="structured-editor-title"><strong>企业图集</strong><label className="outline-btn small upload-button"><ImagePlus size={15} />上传图片<input accept="image/jpeg,image/png,image/webp" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.target.value = ""; }} /></label></div><div className="media-editor-grid">{value.map((row, index) => <article key={`${row.assetId || row.url}-${index}`}><ProtectedMediaImage alt={row.caption || "企业图片"} assetId={row.assetId} src={row.url} /><select value={row.kind} onChange={(event) => update(index, { kind: event.target.value as VendorMedia["kind"] })}><option value="factory">厂房</option><option value="equipment">设备</option><option value="certificate">证书</option></select><input placeholder="图片说明" value={row.caption || ""} onChange={(event) => update(index, { caption: event.target.value })} /><div><button aria-label="上移" disabled={index === 0} type="button" onClick={() => move(index, -1)}><ArrowUp size={15} /></button><button aria-label="下移" disabled={index === value.length - 1} type="button" onClick={() => move(index, 1)}><ArrowDown size={15} /></button><button aria-label="删除图片" type="button" onClick={() => onChange(value.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></div></article>)}</div>{!value.length && <p className="structured-empty">暂无企业图集，可上传厂房、设备和证书图片。</p>}</div>;
}

export function GalleryEditor({ value, onChange }: { value: string; onChange: (raw: string) => void }) {
  const rows = parseJSON<string[]>(value, []);
  return <div className="structured-editor"><div className="structured-editor-title"><strong>产品图库</strong><label className="outline-btn small upload-button"><ImagePlus size={15} />上传图片<input accept="image/*" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadFile(file).then((result) => onChange(JSON.stringify([...rows, result.url]))); event.target.value = ""; }} /></label></div><div className="gallery-editor-grid">{rows.map((url, index) => <article key={`${url}-${index}`}><img alt="" src={url} /><button aria-label="删除图片" type="button" onClick={() => onChange(JSON.stringify(rows.filter((_, rowIndex) => rowIndex !== index)))}><Trash2 size={15} /></button></article>)}</div>{!rows.length && <p className="structured-empty">暂无产品图库。</p>}</div>;
}

export function SpecsEditor({ value, onChange }: { value: string; onChange: (raw: string) => void }) {
  const rows = parseJSON<ProductSpec[]>(value, []);
  const update = (index: number, patch: Partial<ProductSpec>) => onChange(JSON.stringify(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row)));
  return <div className="structured-editor"><div className="structured-editor-title"><strong>规格参数</strong><button className="outline-btn small" type="button" onClick={() => onChange(JSON.stringify([...rows, { name: "", value: "" }]))}><Plus size={15} />添加参数</button></div><div className="spec-editor-list">{rows.map((row, index) => <div key={index}><input aria-label={`参数名 ${index + 1}`} placeholder="参数名，如材质" value={row.name} onChange={(event) => update(index, { name: event.target.value })} /><input aria-label={`参数值 ${index + 1}`} placeholder="参数值" value={row.value} onChange={(event) => update(index, { value: event.target.value })} /><button aria-label="删除参数" type="button" onClick={() => onChange(JSON.stringify(rows.filter((_, rowIndex) => rowIndex !== index)))}><Trash2 size={15} /></button></div>)}</div>{!rows.length && <p className="structured-empty">暂无规格参数。</p>}</div>;
}

const blockLabels: Record<ContentBlockType, string> = { hero: "主视觉", text: "正文", steps: "步骤", cta: "行动按钮", contact: "联系方式", faq: "常见问题" };

export function BlocksEditor({ value, onChange }: { value: string; onChange: (raw: string) => void }) {
  const rows = parseJSON<ContentBlock[]>(value, []);
  const update = (index: number, patch: Partial<ContentBlock>) => onChange(JSON.stringify(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row)));
  return <div className="structured-editor content-block-editor"><div className="structured-editor-title"><strong>结构化内容</strong><select aria-label="添加内容区块" defaultValue="" onChange={(event) => { const type = event.target.value as ContentBlockType; if (type) onChange(JSON.stringify([...rows, { type, title: "", text: "" }])); event.target.value = ""; }}><option value="">添加区块…</option>{Object.entries(blockLabels).map(([type, label]) => <option key={type} value={type}>{label}</option>)}</select></div>{rows.map((block, index) => <article key={index}><header><strong>{blockLabels[block.type]}</strong><button aria-label="删除区块" type="button" onClick={() => onChange(JSON.stringify(rows.filter((_, rowIndex) => rowIndex !== index)))}><Trash2 size={15} /></button></header><input placeholder="区块标题" value={block.title || ""} onChange={(event) => update(index, { title: event.target.value })} /><textarea placeholder="正文说明" value={block.text || ""} onChange={(event) => update(index, { text: event.target.value })} />{["steps", "faq", "text"].includes(block.type) && <textarea placeholder={block.type === "faq" ? "每行一个问题，使用 问题|答案" : "每行一项"} value={(block.items || []).join("\n")} onChange={(event) => update(index, { items: event.target.value.split("\n").filter(Boolean) })} />}{["hero", "cta"].includes(block.type) && <div className="block-inline-fields"><input placeholder="按钮文字" value={block.buttonText || ""} onChange={(event) => update(index, { buttonText: event.target.value })} /><input placeholder="按钮路径" value={block.buttonPath || ""} onChange={(event) => update(index, { buttonPath: event.target.value })} /></div>}{block.type === "contact" && <div className="block-inline-fields"><input placeholder="联系电话" value={block.phone || ""} onChange={(event) => update(index, { phone: event.target.value })} /><input placeholder="微信" value={block.wechat || ""} onChange={(event) => update(index, { wechat: event.target.value })} /></div>}</article>)}{rows.length > 0 && <details className="content-block-preview"><summary>预览内容结构</summary><div>{rows.map((block, index) => <section className={`preview-${block.type}`} key={index}><small>{blockLabels[block.type]}</small>{block.title && <h3>{block.title}</h3>}{block.text && <p>{block.text}</p>}{block.items?.length ? <ol>{block.items.map((item, itemIndex) => <li key={itemIndex}>{item.replace("|", " — ")}</li>)}</ol> : null}{block.buttonText && <span className="primary-btn small">{block.buttonText}</span>}</section>)}</div></details>}{!rows.length && <p className="structured-empty">暂无内容区块，旧版纯文本仍会作为回退显示。</p>}</div>;
}

function parseJSON<T>(value: string, fallback: T): T { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
