import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getVendorAnalytics, type VendorAnalyticsSummary } from "../../api/admin";
import { AdminLayout } from "../../components/admin/AdminLayout";
const labels: Record<string,string> = { contact_phone_click:"电话点击",contact_wechat_copy:"微信号成功复制",contact_wechat_qr_view:"微信二维码查看",vendor_website_click:"官网跳转",site:"站内浏览",share:"推广链接",qr:"推广二维码",unknown:"直接或未知" };
export function VendorAnalyticsPage() {
 const [days,setDays]=useState<7|30|90>(30),[data,setData]=useState<VendorAnalyticsSummary|null>(null),[error,setError]=useState(""),[reload,setReload]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError("");getVendorAnalytics(days).then(row=>{if(active)setData(row);}).catch(()=>{if(active){setData(null);setError("访问数据加载失败，请稍后重试");}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[days,reload]);
 const own=data?.showroom;
 return <AdminLayout title="推广效果"><section className="admin-panel"><header className="admin-section-title"><div><h2>{data?.vendor.name || "本厂"}推广效果</h2><p>从客户浏览到联系操作，了解哪些产品受到关注。</p></div><div className="analytics-range" aria-label="统计时间范围">{([7,30,90] as const).map(n=><button key={n} className={days===n?"active":""} aria-pressed={days===n} onClick={()=>setDays(n)}>近 {n} 天</button>)}</div></header>{loading&&<p role="status">正在加载访问数据…</p>}{error&&<p role="alert">{error}<button className="outline-btn" onClick={()=>setReload(v=>v+1)}>重新加载</button></p>}{!loading&&data&&<>
 <div className="promotion-metric-grid"><article><span>企业展厅访问 / 访客</span><strong>{data.vendor.pv} / {data.vendor.uv}</strong></article><article><span>本厂产品访问 / 访客</span><strong>{own?.productPV ?? 0} / {own?.productUV ?? 0}</strong></article><article><span>有联系操作的访客</span><strong>{own?.contactUV ?? 0}</strong><small>仅统计本厂页面归属数据</small></article><article><span>联系操作转化率</span><strong>{((own?.conversionRate || 0)*100).toFixed(1)}%</strong><small>联系访客 / 本厂页面访客</small></article></div>
 <div className="analytics-grid"><section className="analytics-card"><h3>客户如何联系</h3>{own?.contactEvents.length?<ul className="vendor-contact-events">{own.contactEvents.map(item=><li key={item.label}><span>{labels[item.label]||item.label}</span><strong>{item.count}</strong></li>)}</ul>:<p>暂无联系操作。完善联系方式，再分享本厂产品。</p>}</section><section className="analytics-card"><h3>访问来源</h3>{own?.sources.length?<ul className="vendor-contact-events">{own.sources.map(item=><li key={item.label}><span>{labels[item.label]||"直接或未知"}</span><strong>{item.count}</strong></li>)}</ul>:<p>分享推广链接或二维码后，可在这里查看来源。</p>}</section></div>
 <section className="analytics-card"><h3>受关注的本厂产品</h3>{own?.items.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>产品</th><th>访问次数</th><th>去重访客</th></tr></thead><tbody>{own.items.map(item=><tr key={item.supplierId}><td><Link to={item.path}>{item.name}</Link></td><td>{item.pv}</td><td>{item.uv}</td></tr>)}</tbody></table></div>:<p>暂无本厂产品访问数据，先发布产品并分享给客户。</p>}</section>
 <div className="workspace-checklist"><Link to="/admin/vendor-workspace">查看展厅完善建议与推广入口 →</Link><Link to="/admin/vendor-products">检查图片、型号和过期供货信息 →</Link></div>
 <details className="analytics-card"><summary>平台公共产品热度（非本厂独享曝光）</summary><p>公共产品页 PV / UV：{data.products.pv} / {data.products.uv}。共享产品可能由多家厂商供应，不等同于本厂独立曝光。</p><ul>{data.products.items.map(item=><li key={item.productId}>{item.name}：{item.pv} 次访问</li>)}</ul></details>
 <p className="vendor-analytics-note">访问和操作按现有时间窗口去重，访客为匿名估算。联系操作表示点击、复制或查看，不代表实际接通、添加微信或成交；官网跳转不纳入联系转化。历史公共产品流量不补算为本厂流量。</p>
 </>}</section></AdminLayout>;
}
